services:

  postgres:
    image: postgres:16-alpine
    container_name: honique-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: honique_erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    networks:
      - honique-network

  backend:
    build:
      context: ./backend

    container_name: honique-backend
    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env.docker

    depends_on:
      - postgres

    networks:
      - honique-network

  frontend:
    build:
      context: ./frontend

    container_name: honique-frontend
    restart: unless-stopped

    ports:
      - "5173:5173"

    depends_on:
      - backend

    networks:
      - honique-network

volumes:
  postgres-data:

networks:
  honique-network:
