import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import AdminLayout from "../../../components/AdminLayout/AdminLayout";

import "./InvoicesPage.css";

import {
  getInvoices,
} from "../../../services/api";

function InvoicesPage() {

  const navigate = useNavigate();

  const [invoices, setInvoices] = useState<any[]>([]);

  useEffect(() => {

    loadInvoices();

  }, []);

  async function loadInvoices() {

    try {

      const data =
        await getInvoices();

      setInvoices(data);

    } catch (error) {

      console.error(error);

    }

  }

  return (

    <AdminLayout>

      <div className="orders-page">

        <h1>Invoice Management</h1>

        <p>

          View all invoices generated by Honique ERP.

        </p>

        <table>

          <thead>

            <tr>

              <th>Invoice No</th>
              <th>Customer</th>
              <th>Date</th>
              <th>Total</th>
              <th>Action</th>

            </tr>

          </thead>

          <tbody>

            {invoices.map((invoice) => (

              <tr key={invoice.id}>

                <td>
                  {invoice.invoice_number}
                </td>

                <td>
                  {invoice.customer_name}
                </td>

                <td>

                  {new Date(
                    invoice.invoice_date
                  ).toLocaleDateString("en-IN")}

                </td>

                <td>

                  ₹

                  {Number(
                    invoice.total_amount
                  ).toLocaleString(
                    "en-IN",
                    {
                      minimumFractionDigits: 2,
                      maximumFractionDigits: 2,
                    }
                  )}

                </td>

                <td>

                  <button
                    className="add-btn"
                    onClick={() =>
                      navigate(
                        `/admin/invoices/${invoice.id}`
                      )
                    }
                  >
                    View
                  </button>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

    </AdminLayout>

  );

}

export default InvoicesPage;
